language: node_js
node_js:
- stable
before_script:
script:
before_deploy:
- rm -rf .tmp
- rm -rf .DS_Store
- rm -rf node_modules
- export ELASTIC_BEANSTALK_ENV=rginvitational-api-${TRAVIS_BRANCH}
- zip -r rginvitational_api.zip . -x "*node_modules*" -x ".env*" -x "*.git*" -x ".vscode*" -x ".DS_Store" -x ".*" -x "*mochawesome-report*"
- export ELASTIC_BEANSTALK_LABEL=rginvitational-api-$(git rev-parse --verify HEAD --short)
- export ELASTIC_BEANSTALK_DESCRIPTION=https://github.com/aborskiy/rginvitational_api/tree/$(gitrev-parse HEAD)
after_deploy:
- rm rginvitational-api.zip

deploy:
- provider: elasticbeanstalk
  access_key_id: 
    secure: $ACCESS_KEY_ID
  secret_access_key:
    secure: $SECRET_ACCESS_KEY
  region: "eu-west-1"  
  app: "RGInvitational_API"
  env: "RginvitationalApi-env"
  bucket_name: "rginvitationalapitravisdeployment"
-  provider: pages
  local_dir: mochawesome-report
  skip_cleanup: true
  target_branch: gh-pages
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master