language: node_js
node_js:
- stable
before_script:
script:
before_deploy:
- rm -rf .tmp
- rm -rf .DS_Store
- rm -rf node_modules
- export ELASTIC_BEANSTALK_ENV=rginvitational-api-${TRAVIS_BRANCH}
- zip -r rginvitational_api.zip . -x "*node_modules*" -x ".env*" -x "*.git*" -x ".vscode*" -x ".DS_Store" -x ".*" 
- export ELASTIC_BEANSTALK_LABEL=rginvitational-api-$(git rev-parse --verify HEAD --short)
- export ELASTIC_BEANSTALK_DESCRIPTION=https://github.com/aborskiy/rginvitational_api/tree/$(gitrev-parse HEAD)
after_deploy:
- rm rginvitational-api.zip

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "AKIAJ7U2SORRNZ4BDT7Q"
  secret_access_key:
    secure: "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"
  region: "eu-west-1"  
  app: "RGInvitational_API"
  env: "RginvitationalApi-env"
  bucket_name: "rginvitationalapitravisdeployment"